baseURL = "http://blog.asepsaep.com/"
languageCode = "en-us"
title = "asepsaep"
theme = "hpstr"
pluralizelisttitles = false
PygmentsCodeFences = true
Paginate = 5
disqusShortname = "asepsaep"
globalTitle = "Tes"

[params]
	subtitle = "A Digital Journal"
	[params.author]
		name = "Asep Saepudin"
		avatar = "/images/avatar.jpg"
		bio = "Software Engineer"
		github = "asepsaep"
	[params.image]
	  feature = "/images/front-image.jpg"
	  # credit = "dargadgetz"
	  # creditlink = "http://www.dargadgetz.com/ios-7-abstract-wallpaper-pack-for-iphone-5-and-ipod-touch-retina/"
